Weather app
raheebwa/mv-weather-app pull request #7
Opened 2020-02-26 04:53 UTC by raheebwa

## Features
* [x] Loads data from api
* [x]  Uses async functions / Promises
* [x] UI built with bootstrap

2020-02-26 19:29 UTC, mcrd25 requested changes
# changes Required 🔍 👀 

Hey @raheebwa! 👋 

Great job with this app so far! The code looks good and the repository is very professional! 😄 
However, you are missing one REQUIRED FEATURE! Please read below for further explanation. 👇 

#### Required Changes 
- You are missing the feature that changes the appearance of the app based on weather data. (Color, background image, etc) Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/appearance_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/weather-app)

***Please makes changes and submit another review request.
If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email.***

*Happy coding 😄,*
**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

2020-02-26 19:43 UTC, raheebwa commented
Hey @mcrd25 ,
Please check the app again. The background changes depending on the weather conditon

2020-02-26 19:47 UTC, mcrd25 commented
hi, @raheebwa I will.
I checked many different cities and no change. Different weather conditions and still the same initial image was shown. I will check using your live demo instead of local version now

2020-02-27 15:32 UTC, MauricioRobayo requested changes
Hi!

The app looks great, but I am having the same issues as @mcrd25 and no matter which city I type, I always get the same result. Take a look at this:

![ezgif-1-ce664c76322f](https://user-images.githubusercontent.com/2121481/75457473-80b4b580-594a-11ea-9aed-acb714f2f5d7.gif)

It seems like the request for the city is made, but then the page reloads again with the default city 🤔.

You are submitting a form, be aware of the default event when you submit a form. You want to avoid the default event.

Required changes:

* [ ] Fix bug when submitting a city.
* [ ] The application makes different requests for the Celsius data and the Fahrenheit data (you can get the data for either unit and use math to convert it to the other unit. That beats the point of the assignment) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/requests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622133/)).

Take a look at the [units options](https://openweathermap.org/current#data) on the Open Weather API.

Status: __Request changes__.

2020-02-27 15:32 UTC, MauricioRobayo commented on README.md
> +[Live Demo Link](https://raheebwa.com/mv-weather-app)
This link is broken.

2020-02-27 15:32 UTC, MauricioRobayo commented on src/index.js
> +  utilities.getEl('weather-data').innerHTML = '';
You might want to [prevent the default submit event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit_event).

```js
searchForm.addEventListener('submit', (e) => {
    e.preventDefault();
  utilities.getEl('weather-data').innerHTML = '';
```

2020-03-03 00:17 UTC, shloch approved these changes
![accomplished](https://user-images.githubusercontent.com/40712459/75730235-96c8ca00-5cec-11ea-8e54-dc0b6867d296.jpg)

## GREAT JOB

2020-03-19 22:14 UTC, merged